spring:
  application:
    name: "${project.name}"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: "${db.url}"
    username: '${db.user}'
    password: "${db.password}"
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
      data-source-properties:
        reWriteBatchedInserts: true
  flyway:
    schemas: lim
  jooq:
    sql-dialect: Postgres

server:
  port: "${server.port}"

service:
  default:
    limit: 20
  logging:
    enabled: true
  skipExistedHoldOps: true

management:
  server:
    port: "${management.port}"
  metrics:
    export:
      prometheus:
        enabled: false
    tags:
      application: "${project.name}"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

testcontainers:
  postgresql:
    tag: '11.4'